spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    ?? PC? ????? Database??? ?? ???.
    url: jdbc:mysql://3.38.117.32:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # Database?? ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql? ??? ??? ?? ??? ?? ???.
    username: okks3579
    password: Tjddbswkd12!@ # ??? mysql ????
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: root
      password: root
      roles:
        - ADMIN
logging:
  level:
    root: info